// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhwwvmhsmofucgejqpcm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpod3d2bWhzbW9mdWNnZWpxcGNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk4OTczMDUsImV4cCI6MjA4NTQ3MzMwNX0.-v4imVscB3udWpCAYMe6FPyYVtbMJ8oupKTZc0FspX4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});